<template>
  <!-- 元件：vue-loading-overlay -->
    <div class="loadingio-spinner-spinner-r9nl8ighj1">
      <div class="ldio-7oudh8cl7et">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
</template>

<script>
export default {
  name: 'VueLoading',
};
</script>

<style>
@keyframes ldio-7oudh8cl7et {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-7oudh8cl7et div {
  left: 71.91px;
  top: 36.72px;
  position: absolute;
  animation: ldio-7oudh8cl7et linear 1s infinite;
  background: #f15675;
  width: 9.18px;
  height: 18.36px;
  border-radius: 4.59px / 9.18px;
  transform-origin: 4.59px 39.78px;
}
.ldio-7oudh8cl7et div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #f15675;
}
.ldio-7oudh8cl7et div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #f15675;
}
.loadingio-spinner-spinner-r9nl8ighj1 {
  width: 153px;
  height: 153px;
  display: inline-block;
  overflow: hidden;
  background: rgba(NaN, NaN, NaN, 0);
}
.ldio-7oudh8cl7et {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-7oudh8cl7et div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
